// <auto-generated />
using System;
using CRUDDelicious.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDDelicious.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20200612193703_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRUDDelicious.Models.Dish", b =>
                {
                    b.Property<int>("DiSId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChefName");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Description");

                    b.Property<string>("DishName");

                    b.Property<string>("Tastiness");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<int>("calories");

                    b.HasKey("DiSId");

                    b.ToTable("Dishes");
                });
#pragma warning restore 612, 618
        }
    }
}
